name: conda-lock-dev
category: dev
channels:
- conda-forge
- nodefaults
dependencies:
- black
- check-manifest
- doctr
- filelock
- python-build
- freezegun
- isort
- mypy
- pre-commit
- pytest
- pytest-cov
- pytest-xdist
- pytest-timeout
- requests-mock
- tomli
- twine
- wheel
- mkdocs
- mkdocs-material
- mkdocs-click
- mkdocs-include-markdown-plugin
- flaky
- docker-py
- gitpython
- pip
